dist: trusty
sudo: false
group: beta
language: node_js
node_js:
- node
addons:
  firefox: 49.0.2
cache:
  directories:
  - node_modules
  - "$HOME/.cache/bower"
before_install:
- if [ -d node_modules ] && [ x$(cat node_modules/.last-node-version 2>/dev/null)
  != x$(node -e 'console.log(process.version)') ]; then npm rebuild && node -e 'console.log(process.version)'
  > node_modules/.last-node-version; fi
before_script:
- npm install web-component-tester bower@1.7.9 polylint
- "$(npm bin)/bower install"
- "$(npm bin)/polylint --no-recursion"
script:
- xvfb-run $(npm bin)/wct
after_success: '[ ${TRAVIS_PULL_REQUEST} = "false" ] && [ ${TRAVIS_BRANCH} = "master"
  ] && $(npm bin)/bower install -s https://${GH_TOKEN}@github.com/Collaborne/collaborne-build-tools.git
  && bower_components/collaborne-build-tools/gpages_build.sh Collaborne info@collaborne.com'
notifications:
  slack:
    secure: EkUJENk5OEEXSgxy+xLDHrThp9p8bhaksg0ZGAZHw2DOKN7VNpzECeIpg2OkA8CCN12PWqb68WUlzf17tafMvy724+BHi/aUeXzD75tZriUL6TVRh9KNg7J1yUY0mO+BHfuL66MbxuilE4/EYqNvRA5obxKyo/hJFyAHmb8J0o2NEGAKfID/k0Ch/7AmY50jYVJo3OdfzLaMv+oKSU5Kn8UvGRZaJdEB6TGqtvQNsgEW2Mbm0ePHarQYYdfU0QmpGUfbL3QxEO2AURl5rYArVo0WhBI+UUlnMcKjyyQ2N/m4C3UMmdhWT8M7NbJ/uDcmMX57r9avINOjz6efmiZTTujHitAdq/5moQxZNpefZOdVjK8xZ1h6Lrx4VJm5Va0AcHUkABbNi9ADM3fR4CZxU4KslRe65hR+Y6gYZaz2VIe3zsMKiO9SUv+eHdrEjtJLoYfTKM7tOOQzo/W3cV2esswYxm2+vdDQwOhUNG1RdAyTS987gC75nvE+nFFqC65Tv5CgpDucRJyhzKWcMJhYXOVD2zA5tCI9zPQgcrAwszK8EovCYG5t/jv70zhdo0ymHkuHIshZtagO+rmZQv/HNF2vf7f5SVQ85Gb+eJpVWRiAyKWaW1qpiPWCZ1qAAvqg9YUKnhW/QtiKyVW8eP/jiIwKXNK7kI1hUTjavbZ6Tkg=
after_failure:
- after_failure
